### ISSUE TITLE
Version 2.0.1 does not work in ClojureScript

### ISSUE THREAD

**Issue by ivarref** [ptaoussanis/tufte#33]
Content of `deps.edn`:
```clojure
{:deps {org.clojure/clojurescript {:mvn/version "1.10.339"}
        com.taoensso/tufte        {:mvn/version "2.0.1"}}}
```

Content of `src/hello_world/core.cljs`:
```clojure

(ns hello-world.core
  (:require [taoensso.tufte :as tufte :refer-macros (defnp p profiled profile)]))

(tufte/add-basic-println-handler! {})

(defn get-x []
  (+ 1 1))

(defn get-y []
  (+ 2 2))

(profile ; Profile any `p` forms called during body execution
  {} ; Profiling options; we'll use the defaults for now
  (dotimes [_ 5]
    (p :get-x (get-x))
    (p :get-y (get-y))))
```

Example output:
```bash
$ clj -m cljs.main --target node --output-to main.js -c hello-world.core && node ./main.js

/home/ire/code/learn/deps-edn/out/cljs/core.cljs:312
  (let [ty (type obj)
  ^
Error: No protocol method IDeref.-deref defined for type cljs.core/Cons: (taoensso.encore/if-cljs (cljs.core/array) (LinkedList.))
    at Object.cljs$core$missing_protocol [as missing_protocol] (/home/ire/code/learn/deps-edn/out/cljs/core.cljs:312:3)
    at Object.cljs.core/missing-protocol [as _deref] (/home/ire/code/learn/deps-edn/out/cljs/core.cljs:671:1)
    at cljs.core/-deref (/home/ire/code/learn/deps-edn/out/cljs/core.cljs:1449:4)
    at cljs.core/deref (/home/ire/code/learn/deps-edn/out/taoensso/tufte/impl.cljc:240:15)
    at taoensso$tufte$impl$capture_time_BANG_ (/home/ire/code/learn/deps-edn/out/taoensso/tufte/impl.js:376:3)
    at taoensso.tufte.impl/capture-time! (/home/ire/code/learn/deps-edn/out/hello_world/core.cljs:6:1)
    at /home/ire/code/learn/deps-edn/out/hello_world/core.cljs:15:5
    at /home/ire/code/learn/deps-edn/out/hello_world/core.js:101:3
    at Object.<anonymous> (/home/ire/code/learn/deps-edn/out/hello_world/core.js:103:4)
    at Module._compile (module.js:653:30)
```

**Comment by borkdude** [comment]
Also running into this one.

**Comment by ptaoussanis** [comment]
Hi there-

Would unfortunately need some more details to help identify the problem. For example:

- Do earlier versions of Tufte work?
- Do earlier versions of ClojureScript work?
- Have you tried checking for dependency conflicts (e.g. with `lein deps :tree`)?

Thanks!

**Comment by borkdude** [comment]
Try the following example:
```
(require '[taoensso.tufte :as tufte :refer-macros (defnp p profiled profile)])
(profile {} (dotimes [_ 10000] (p :foo (+ 1 2 3))))
```
Works with:
```
clj -Srepro -Sdeps '{:deps {com.taoensso/tufte {:mvn/version "1.4.0"} org.clojure/clojurescript {:mvn/version "1.10.439"}}}' -m cljs.main -re node -r
```
but breaks with versions `2.0.0` and `2.0.1` of Tufte.

**Comment by ptaoussanis** [comment]
Great, thanks Michiel! Will try take a look later this week.

**Comment by borkdude** [comment]
Thanks Peter. Also worth trying without the `-re node` flag. cljs.main will open a browser tab and run the code in there. I'm not sure if Tufte should work in the browser, but I also get an error there.

**Comment by ptaoussanis** [comment]
👍 Great, thanks. Am very limited on free time atm, so any debug info you (or anyone else) can provide would be very helpful (+ makes it more likely that I can respond quickly).

**Comment by borkdude** [comment]
More detail: when I print the result of `(atom? acc)` I get this:

```
(taoensso.encore/if-cljs (cljs.core/instance? cljs.core.Atom nil) (cljs.core/instance? clojure.lang.Atom nil))
```
so maybe the problem is with the `atom?` macro.

**Comment by ptaoussanis** [comment]
Hoping to try take a look at this in the next couple weeks, sorry for the delay.

**Comment by ptaoussanis** [comment]
Just deployed `[com.taoensso/tufte "2.1.0-alpha1"]` to Clojars which should fix.

Thank you both for the clear report and assistance; really helped me to squeeze this in quickly between other work.
