### ISSUE TITLE
Breaks uberjars due to NoClassDefFoundError when trying to call encore/read-sys-val

### ISSUE THREAD

**Issue by zilti** [ptaoussanis/tufte#59]
I am not sure why this happens, but I noticed that while my program (based on Fulcro and Fulcro RAD) runs fine when being started "from source", but when building an uberjar and trying to run it, it errors out:

```
Exception in thread "main" java.lang.NoClassDefFoundError: taoensso/encore$read_sys_val
        at taoensso.tufte$fn__31180.invokeStatic(tufte.cljc:129)
        at taoensso.tufte$fn__31180.invoke(tufte.cljc:129)
        at taoensso.tufte__init.load(Unknown Source)
        at taoensso.tufte__init.<clinit>(Unknown Source)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at clojure.lang.RT.classForName(RT.java:2211)
        at clojure.lang.RT.classForName(RT.java:2220)
        at clojure.lang.RT.loadClassForName(RT.java:2239)
        at clojure.lang.RT.load(RT.java:449)
        at clojure.lang.RT.load(RT.java:424)
        at clojure.core$load$fn__6839.invoke(core.clj:6126)
        at clojure.core$load.invokeStatic(core.clj:6125)
        at clojure.core$load.doInvoke(core.clj:6109)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invokeStatic(core.clj:5908)
        at clojure.core$load_one.invoke(core.clj:5903)
        at clojure.core$load_lib$fn__6780.invoke(core.clj:5948)
        at clojure.core$load_lib.invokeStatic(core.clj:5947)
        at clojure.core$load_lib.doInvoke(core.clj:5928)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$load_libs.invokeStatic(core.clj:5985)
        at clojure.core$load_libs.doInvoke(core.clj:5969)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$require.invokeStatic(core.clj:6007)
```

This is with Encore 2.122.0 and Tufte 2.1.0.

**Comment by ptaoussanis** [comment]
@zilti Hi Daniel, could you please try the instructions [here](https://github.com/ptaoussanis/encore#recommended-steps-after-any-significant-dependency-update) and confirm if you're still having trouble after? Thanks!

**Comment by zilti** [comment]
I fetched the deps cleanly, even went as far as deleting `~/.m2` and `.cpcache`. What solved it in the end is that I manually called `(compile 'taoensso.encore)` before trying to build the uberjar with aot compilation. (I am using the deps.edn tooling and seancorfield/depstar to build the jar)
